(()=>{
const $=s=>document.querySelector(s);let ctx;
function audio(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(midi,d=.28,at=0){const c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+at;o.frequency.value=440*Math.pow(2,(midi-69)/12);o.type='sine';g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.2,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+d+.03)}
function seq(notes){notes.forEach((n,i)=>tone(n,.3,i*.48))}
const cards=$('#chooser');if(!cards)return;
const defs=[{id:'rhythm',icon:'🥁',title:'Ритмическое эхо',text:'Начни с трёх ударов и постепенно переходи к более длинным ритмическим рисункам.',action:'Слушать ритм'},{id:'sing',icon:'🎤',title:'Повтори мелодию голосом',text:'Начни с 2–3 звуков и постепенно переходи к более длинным мелодиям.',action:'Слушать мелодию'}];
defs.forEach(d=>{const b=document.createElement('button');b.className='game-card creative-card';b.dataset.creative=d.id;b.innerHTML=`<span class="icon">${d.icon}</span><h2>${d.title}</h2><p>${d.text}</p><span class="go">Играть →</span>`;cards.appendChild(b)});
const section=document.createElement('section');section.id='creativeGame';section.className='game hidden';section.innerHTML=`<button class="back-games" id="creativeBack">← Все игры</button><div class="game-head"><div><div class="eyebrow">Музыкальный тренажёр</div><h2 id="creativeTitle"></h2></div><div class="score"><strong id="creativeCount">0</strong><small>попыток</small></div></div><p class="muted" id="creativeText"></p><div id="creativeLevels" class="level-row"></div><div class="play-zone"><button id="creativeListen" class="listen">▶<span id="creativeAction"></span></button></div><div id="creativeArea"></div><div id="creativeFeedback" class="feedback"></div><button id="creativeNext" class="primary hidden">Следующее упражнение →</button>`;document.querySelector('.wrap').appendChild(section);
let mode='',count=0,targetRhythm=[],taps=[],tapStart=0,targetNotes=[],stream=null,raf=0,rhythmLocked=false,singLevel=1,rhythmLevel=1;
function open(id){mode=id;count=0;$('#chooser').classList.add('hidden');document.querySelectorAll('.game').forEach(x=>x.classList.add('hidden'));section.classList.remove('hidden');const d=defs.find(x=>x.id===id);$('#creativeTitle').textContent=d.title;$('#creativeText').textContent=d.text;$('#creativeAction').textContent=d.action;$('#creativeCount').textContent='0';$('#creativeFeedback').textContent='';$('#creativeNext').classList.add('hidden');setupLevels();render()}
function setupLevels(){const el=$('#creativeLevels'),cur=mode==='rhythm'?rhythmLevel:singLevel;el.innerHTML='<span>Уровень:</span>'+[1,2,3].map(n=>`<button class="level ${n===cur?'on':''}" data-level="${n}">${n}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(mode==='rhythm')rhythmLevel=+b.dataset.level;else singLevel=+b.dataset.level;setupLevels();render();$('#creativeFeedback').textContent='';$('#creativeNext').classList.add('hidden')})}
function singRange(){return singLevel===1?[2,3]:singLevel===2?[4,5]:[3,4,5,6]}
function rhythmCount(){return rhythmLevel===1?3:rhythmLevel===2?4:5}
function render(){stopMic();const a=$('#creativeArea');if(mode==='rhythm'){const n=rhythmCount(),desc=rhythmLevel===1?'Три удара: самые короткие рисунки «ти-ти-та», «та-ти-ти».':rhythmLevel===2?'Четыре удара: рисунок становится длиннее.':'Пять ударов: больше вариантов коротких и длинных промежутков.';a.innerHTML=`<div class="creative-prompt"><strong>Уровень ${rhythmLevel} · ${n} удара</strong><br>${desc}<br>Сначала послушай, затем повтори касаниями.</div><div id="rhythmStatus" class="feedback">Нажми «Слушать ритм».</div><button id="tapPad" class="tap-pad" type="button">ТАП<br><small>0 / ${n}</small></button><div id="tapDots" class="tap-dots"></div><button id="nextRhythm" class="primary hidden" type="button">Следующее упражнение →</button>`;$('#tapPad').onclick=tap;$('#nextRhythm').onclick=nextRhythm}else{a.innerHTML=`<div class="creative-prompt"><strong>Уровень ${singLevel}</strong><br>${singLevel===1?'Маленькие мотивы: 2–3 звука.':singLevel===2?'Мотивы средней длины: 4–5 звуков.':'Разные мотивы: 3–6 звуков.'}<br>Послушай, затем нажми микрофон и пропой мелодию без слов.</div><button id="startSing" class="primary creative-done" type="button">🎤 Начать петь</button><div id="pitchLive" class="feedback"></div>`;$('#startSing').onclick=startMic}}
function tap(){const n=rhythmCount();if(rhythmLocked||!targetRhythm.length){feedback('Сначала нажми «Слушать ритм».');return}const now=performance.now();if(!taps.length)tapStart=now;taps.push((now-tapStart)/1000);tone(60,.06);const dot=document.createElement('i');$('#tapDots').appendChild(dot);$('#tapPad small').textContent=`${taps.length} / ${n}`;if(taps.length===n){rhythmLocked=true;setTimeout(scoreRhythm,180)}}
function scoreRhythm(){const ti=targetRhythm.slice(1).map((x,i)=>x-targetRhythm[i]),ui=taps.slice(1).map((x,i)=>x-taps[i]);const ts=ti.reduce((a,b)=>a+b,0),us=Math.max(.01,ui.reduce((a,b)=>a+b,0)),scale=ts/us;const errs=ti.map((x,i)=>Math.abs(x-ui[i]*scale)/Math.max(.08,x)),err=errs.reduce((a,b)=>a+b,0)/errs.length,pct=Math.max(0,Math.min(100,Math.round(100*(1-err))));count++;$('#creativeCount').textContent=count;feedback(pct>=88?`Отлично — ${pct}%! Рисунок совпал.`:pct>=70?`Очень близко — ${pct}%.`:`Сейчас ${pct}%. Послушай ещё раз, где удары ближе друг к другу.`);$('#nextRhythm').classList.remove('hidden')}
function nextRhythm(){render();play()}
function feedback(x){$('#creativeFeedback').innerHTML=`<strong>${x}</strong>`}
function makeRhythm(n){if(n===3){const p=[[0,.28,.56],[0,.52,.80],[0,.28,.80],[0,.42,.84],[0,.58,.86]];return p[Math.floor(Math.random()*p.length)]}const intervals=n===4?[[.28,.28,.55],[.5,.25,.25],[.25,.5,.25],[.25,.25,.5],[.4,.2,.4]]:[[.25,.25,.5,.25],[.5,.25,.25,.5],[.25,.5,.25,.25],[.4,.2,.2,.4],[.25,.25,.25,.5]];const ints=intervals[Math.floor(Math.random()*intervals.length)],out=[0];ints.forEach(x=>out.push(out[out.length-1]+x));return out}
function makeMelody(n){const base=60+Math.floor(Math.random()*5),steps=[-2,-1,1,2,3];let notes=[base];while(notes.length<n){let next=notes[notes.length-1]+steps[Math.floor(Math.random()*steps.length)];if(next<57||next>69)next=base;notes.push(next)}return notes}
function play(){if(mode==='rhythm'){targetRhythm=makeRhythm(rhythmCount());taps=[];rhythmLocked=false;targetRhythm.forEach(t=>tone(48,.07,t));if($('#tapDots'))$('#tapDots').innerHTML='';if($('#tapPad small'))$('#tapPad small').textContent=`0 / ${rhythmCount()}`;if($('#nextRhythm'))$('#nextRhythm').classList.add('hidden');$('#creativeFeedback').textContent=''}else{const range=singRange(),n=range[Math.floor(Math.random()*range.length)];targetNotes=makeMelody(n);seq(targetNotes);feedback(`Запомни ${n} ${n===2?'звука':n<5?'звука':'звуков'} и повтори голосом.`)}}
function autoCorrelate(buf,sr){let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);if(rms<.015)return-1;let best=-1,bestCorr=0;for(let off=Math.floor(sr/900);off<Math.min(Math.floor(sr/80),buf.length/2);off++){let c=0;for(let i=0;i<buf.length-off;i++)c+=buf[i]*buf[i+off];if(c>bestCorr){bestCorr=c;best=off}}return best>0?sr/best:-1}
async function startMic(){if(!targetNotes.length){feedback('Сначала нажми «Слушать мелодию».');return}try{stopMic();stream=await navigator.mediaDevices.getUserMedia({audio:true});const c=audio(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=2048;src.connect(an);const buf=new Float32Array(an.fftSize),samples=[],start=performance.now(),listenMs=Math.max(2600,targetNotes.length*750);$('#startSing').textContent='Слушаю…';function loop(){an.getFloatTimeDomainData(buf);const hz=autoCorrelate(buf,c.sampleRate);if(hz>70&&hz<1000)samples.push({t:performance.now()-start,m:69+12*Math.log2(hz/440)});if(performance.now()-start<listenMs){raf=requestAnimationFrame(loop);return}stopMic();analyseSong(samples)}loop()}catch(e){feedback('Не удалось включить микрофон. Разреши доступ к микрофону и попробуй снова.')}}
function analyseSong(s){const n=targetNotes.length;if(s.length<Math.max(5,n*2)){feedback('Я почти не услышал голос. Попробуй спеть чуть громче и протяжнее.');render();return}const dur=s[s.length-1].t,parts=Array.from({length:n},(_,k)=>s.filter(x=>x.t>=dur*k/n&&x.t<dur*(k+1)/n).map(x=>x.m)).map(a=>a.length?a.sort((x,y)=>x-y)[Math.floor(a.length/2)]:null);if(parts.some(x=>x==null)){feedback(`Не все ${n} звука удалось услышать. Попробуй ещё раз.`);render();return}const dir=a=>a.slice(1).map((x,i)=>Math.abs(x-a[i])<.6?0:Math.sign(x-a[i])),want=dir(targetNotes),got=dir(parts);let ok=0;want.forEach((x,i)=>{if(x===got[i])ok++});count++;$('#creativeCount').textContent=count;const total=n-1;feedback(ok===total?`Отлично! Все ${total} движения мелодии совпали.`:`Совпало ${ok} из ${total} движений. Послушай и попробуй ещё раз.`);$('#pitchLive').textContent=`Мелодия: ${n} звука. Проверяем направление между соседними звуками.`;$('#creativeNext').classList.remove('hidden')}
function stopMic(){if(raf)cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
document.querySelectorAll('[data-creative]').forEach(b=>b.onclick=()=>open(b.dataset.creative));$('#creativeListen').onclick=play;$('#creativeNext').onclick=()=>{render();$('#creativeFeedback').textContent='';$('#creativeNext').classList.add('hidden');play()};$('#creativeBack').onclick=()=>{stopMic();section.classList.add('hidden');$('#chooser').classList.remove('hidden')};
})();