(()=>{
const $=s=>document.querySelector(s);let ctx;
function audio(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(midi,d=.28,at=0){const c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+at;o.frequency.value=440*Math.pow(2,(midi-69)/12);o.type='sine';g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.2,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+d+.03)}
function seq(notes){notes.forEach((n,i)=>tone(n,.32,i*.52))}
const cards=$('#chooser');if(!cards)return;
const defs=[{id:'rhythm',icon:'🥁',title:'Ритмическое эхо',text:'Слушай короткий ритм и повторяй его касаниями — от 3 до 5 ударов.',action:'Слушать ещё раз'},{id:'sing',icon:'🎤',title:'Повтори мелодию голосом',text:'Слушай и повторяй голосом — от маленьких мотивов из 2–3 звуков до цепочек из 6.',action:'Слушать ещё раз'}];
defs.forEach(d=>{const b=document.createElement('button');b.className='game-card creative-card';b.dataset.creative=d.id;b.innerHTML=`<span class="icon">${d.icon}</span><h2>${d.title}</h2><p>${d.text}</p><span class="go">Играть →</span>`;cards.appendChild(b)});
const section=document.createElement('section');section.id='creativeGame';section.className='game hidden';section.innerHTML=`<button class="back-games" id="creativeBack">← Все игры</button><div class="game-head"><div><div class="eyebrow">Музыкальный тренажёр</div><h2 id="creativeTitle"></h2></div><div class="score"><strong id="creativeCount">0</strong><small>заданий</small></div></div><p class="muted" id="creativeText"></p><div id="creativeLevels" class="level-row"></div><div id="roundProgress" class="creative-prompt"></div><div class="play-zone"><button id="creativeListen" class="listen">▶ <span id="creativeAction"></span></button></div><div id="creativeArea"></div><div id="creativeFeedback" class="feedback" aria-live="polite"></div><div id="creativeActions" class="level-row hidden"><button id="creativeRetry" class="level">↻ Повторить это</button><button id="creativeNext" class="primary">Следующее →</button></div>`;document.querySelector('.wrap').appendChild(section);
let mode='',count=0,targetRhythm=[],taps=[],tapStart=0,targetNotes=[],stream=null,raf=0,rhythmLocked=false,singLevel=1,rhythmLevel=1,round=1,correct=0;
function curLevel(){return mode==='rhythm'?rhythmLevel:singLevel}
function open(id){mode=id;count=0;round=1;correct=0;targetRhythm=[];targetNotes=[];$('#chooser').classList.add('hidden');document.querySelectorAll('.game').forEach(x=>x.classList.add('hidden'));section.classList.remove('hidden');const d=defs.find(x=>x.id===id);$('#creativeTitle').textContent=d.title;$('#creativeText').textContent=d.text;$('#creativeAction').textContent=d.action;$('#creativeCount').textContent='0';setupLevels();render();updateProgress()}
function setupLevels(){const el=$('#creativeLevels'),cur=curLevel();el.innerHTML='<span>Уровень:</span>'+[1,2,3].map(n=>`<button class="level ${n===cur?'on':''}" data-level="${n}">${n}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(mode==='rhythm')rhythmLevel=+b.dataset.level;else singLevel=+b.dataset.level;round=1;correct=0;targetRhythm=[];targetNotes=[];setupLevels();render();updateProgress()})}
function updateProgress(){const stars='★'.repeat(correct)+'☆'.repeat(Math.max(0,5-correct));$('#roundProgress').innerHTML=`<strong>Задание ${Math.min(round,5)} из 5</strong><br><span style="letter-spacing:5px">${stars}</span><br><small>После пяти заданий увидишь результат уровня.</small>`}
function singRange(){return singLevel===1?[2,3]:singLevel===2?[4,5]:[3,4,5,6]}
function rhythmCount(){return rhythmLevel===1?3:rhythmLevel===2?4:5}
function render(){stopMic();$('#creativeFeedback').textContent='';$('#creativeActions').classList.add('hidden');const a=$('#creativeArea');if(mode==='rhythm'){const n=rhythmCount(),desc=rhythmLevel===1?'Самые короткие рисунки: три удара.':rhythmLevel===2?'Четыре удара: удерживаем рисунок чуть дольше.':'Пять ударов: тренируем более длинную ритмическую память.';a.innerHTML=`<div class="creative-prompt"><strong>Уровень ${rhythmLevel}</strong><br>${desc}</div><div id="rhythmStatus" class="feedback">Нажми «Слушать ещё раз», затем повтори.</div><button id="tapPad" class="tap-pad" type="button">ТАП<br><small>0 / ${n}</small></button><div id="tapDots" class="tap-dots"></div>`;$('#tapPad').onclick=tap}else{a.innerHTML=`<div class="creative-prompt"><strong>Уровень ${singLevel}</strong><br>${singLevel===1?'2–3 звука. Небольшие шаги по гамме и простые терции.':singLevel===2?'4–5 звуков. Короткие музыкальные мотивы с изменением направления.':'3–6 звуков. Более длинные мотивы и более широкий диапазон.'}<br><small>Можно начать на своей удобной высоте: игра сравнивает отношения между звуками, а не абсолютную ноту. Между звуками можно делать маленькие паузы.</small></div><button id="startSing" class="primary creative-done" type="button">🎤 Я готов(а) петь</button><div id="pitchLive" class="feedback"></div><div id="contourView" class="creative-prompt hidden"></div>`;$('#startSing').onclick=startMic}}
function tap(){const n=rhythmCount();if(rhythmLocked||!targetRhythm.length){feedback('Сначала послушай ритм.');return}const now=performance.now();if(!taps.length)tapStart=now;taps.push((now-tapStart)/1000);tone(60,.06);const dot=document.createElement('i');$('#tapDots').appendChild(dot);$('#tapPad small').textContent=`${taps.length} / ${n}`;if(taps.length===n){rhythmLocked=true;setTimeout(scoreRhythm,180)}}
function scoreRhythm(){const ti=targetRhythm.slice(1).map((x,i)=>x-targetRhythm[i]),ui=taps.slice(1).map((x,i)=>x-taps[i]);const ts=ti.reduce((a,b)=>a+b,0),us=Math.max(.01,ui.reduce((a,b)=>a+b,0)),scale=ts/us;const errs=ti.map((x,i)=>Math.abs(x-ui[i]*scale)/Math.max(.08,x)),err=errs.reduce((a,b)=>a+b,0)/errs.length,pct=Math.max(0,Math.min(100,Math.round(100*(1-err))));finishAttempt(pct>=78,pct>=88?`Точно! ${pct}%.`:pct>=78?`Очень близко — ${pct}%.`:`Получилось ${pct}%. Послушай образец ещё раз.`)}
function feedback(x){$('#creativeFeedback').innerHTML=`<strong>${x}</strong>`}
function makeRhythm(n){if(n===3){const p=[[0,.28,.56],[0,.52,.80],[0,.28,.80],[0,.42,.84],[0,.58,.86]];return p[Math.floor(Math.random()*p.length)]}const intervals=n===4?[[.28,.28,.55],[.5,.25,.25],[.25,.5,.25],[.25,.25,.5],[.4,.2,.4]]:[[.25,.25,.5,.25],[.5,.25,.25,.5],[.25,.5,.25,.25],[.4,.2,.2,.4],[.25,.25,.25,.5]];const ints=intervals[Math.floor(Math.random()*intervals.length)],out=[0];ints.forEach(x=>out.push(out[out.length-1]+x));return out}
const SCALE=[0,2,4,5,7,9,11,12];
function makeMelody(n){const tonic=60+Math.floor(Math.random()*3),maxDegree=singLevel===1?4:singLevel===2?6:7;let degree=Math.floor(Math.random()*Math.min(4,maxDegree)),degrees=[degree];while(degrees.length<n){const moves=singLevel===1?[-2,-1,1,2]:singLevel===2?[-3,-2,-1,1,2,3]:[-4,-3,-2,-1,1,2,3,4];let next=degree+moves[Math.floor(Math.random()*moves.length)];if(next<0||next>maxDegree)next=degree+(next<0?1:-1);if(next===degree)next=Math.min(maxDegree,degree+1);degree=next;degrees.push(degree)}return degrees.map(d=>tonic+SCALE[d])}
function play(newExercise=false){if(mode==='rhythm'){if(newExercise||!targetRhythm.length)targetRhythm=makeRhythm(rhythmCount());taps=[];rhythmLocked=false;targetRhythm.forEach(t=>tone(48,.07,t));if($('#tapDots'))$('#tapDots').innerHTML='';if($('#tapPad small'))$('#tapPad small').textContent=`0 / ${rhythmCount()}`;feedback('Теперь повтори услышанный рисунок.')}else{if(newExercise||!targetNotes.length){const range=singRange(),n=range[Math.floor(Math.random()*range.length)];targetNotes=makeMelody(n)}seq(targetNotes);feedback(`Сейчас ${targetNotes.length} ${targetNotes.length===2?'звука':targetNotes.length<5?'звука':'звуков'}. Послушай и повтори.`);if($('#contourView'))$('#contourView').classList.add('hidden')}}
function median(a){if(!a.length)return null;const b=[...a].sort((x,y)=>x-y);return b[Math.floor(b.length/2)]}
function pitchFromBuffer(buf,sr){let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);if(rms<.012)return-1;const minLag=Math.floor(sr/900),maxLag=Math.min(Math.floor(sr/80),buf.length/2);let bestLag=-1,best=-1;for(let lag=minLag;lag<=maxLag;lag++){let num=0,e1=0,e2=0;for(let i=0;i<buf.length-lag;i++){const a=buf[i],b=buf[i+lag];num+=a*b;e1+=a*a;e2+=b*b}const corr=num/Math.sqrt(Math.max(1e-9,e1*e2));if(corr>best){best=corr;bestLag=lag}}if(best<.55||bestLag<0)return-1;return sr/bestLag}
function repairOctaves(samples){let prev=null;return samples.map(x=>{let m=x.m;if(prev!=null){while(m-prev>7)m-=12;while(prev-m>7)m+=12}prev=m;return{...x,m}})}
function smoothSamples(samples){const s=repairOctaves(samples),out=[];for(let i=0;i<s.length;i++){const w=s.slice(Math.max(0,i-2),Math.min(s.length,i+3)).map(x=>x.m);out.push({...s[i],m:median(w)})}return out}
function stablePitchRuns(samples){const s=smoothSamples(samples);if(!s.length)return[];const runs=[];let cur=[s[0]];for(let i=1;i<s.length;i++){const base=median(cur.slice(-8).map(x=>x.m));const gap=s[i].t-s[i-1].t;if(gap>180||Math.abs(s[i].m-base)>1.25){if(cur.length>=3)runs.push(cur);cur=[s[i]]}else cur.push(s[i])}if(cur.length>=3)runs.push(cur);return runs.map(r=>({m:median(r.map(x=>x.m)),t0:r[0].t,t1:r[r.length-1].t,len:r.length})).filter(r=>r.t1-r.t0>=70||r.len>=5)}
function extractNotes(samples,n){let runs=stablePitchRuns(samples);if(runs.length===n)return runs.map(r=>r.m);if(runs.length>n){while(runs.length>n){let best=0,bestGap=Infinity;for(let i=0;i<runs.length-1;i++){const gap=Math.abs(runs[i+1].m-runs[i].m)+(runs[i+1].t0-runs[i].t1)/220;if(gap<bestGap){bestGap=gap;best=i}}const a=runs[best],b=runs[best+1],w=a.len+b.len;runs.splice(best,2,{m:(a.m*a.len+b.m*b.len)/w,t0:a.t0,t1:b.t1,len:w})}return runs.map(r=>r.m)}
const s=smoothSamples(samples);if(!s.length)return[];const start=s[0].t,end=s[s.length-1].t,dur=Math.max(1,end-start);return Array.from({length:n},(_,k)=>{const lo=start+dur*k/n,hi=start+dur*(k+1)/n;const vals=s.filter(x=>x.t>=lo&&x.t<(k===n-1?hi+1:hi)).map(x=>x.m);if(vals.length<2)return null;const m=median(vals),close=vals.filter(v=>Math.abs(v-m)<1.5);return median(close.length?close:vals)})}
function arrows(intervals){return intervals.map(x=>Math.abs(x)<.6?'→':x>0?'↑':'↓').join(' ')}
async function startMic(){if(!targetNotes.length){feedback('Сначала послушай мелодию.');return}try{stopMic();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const c=audio(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=2048;an.smoothingTimeConstant=.15;src.connect(an);const buf=new Float32Array(an.fftSize),samples=[],start=performance.now(),listenMs=Math.max(2200,targetNotes.length*820);$('#startSing').disabled=true;$('#startSing').textContent='🎤 Слушаю тебя…';function loop(){an.getFloatTimeDomainData(buf);const hz=pitchFromBuffer(buf,c.sampleRate);if(hz>70&&hz<1000)samples.push({t:performance.now()-start,m:69+12*Math.log2(hz/440)});if(performance.now()-start<listenMs){raf=requestAnimationFrame(loop);return}stopMic();analyseSong(samples)}loop()}catch(e){feedback('Не удалось включить микрофон. Разреши доступ к микрофону и попробуй снова.');resetSingButton()}}
function resetSingButton(text='🎤 Попробовать ещё раз'){if($('#startSing')){$('#startSing').disabled=false;$('#startSing').textContent=text}}
function analyseSong(raw){const n=targetNotes.length;if(raw.length<Math.max(8,n*3)){feedback('Я почти не услышал устойчивый голос. Попробуй петь чуть громче и держать каждый звук немного дольше.');resetSingButton();return}const heard=extractNotes(raw,n);if(heard.length!==n||heard.some(x=>x==null)){feedback(`Я не смог уверенно услышать все ${n} звука. Попробуй разделить их маленькими паузами.`);resetSingButton();return}const wantIntervals=targetNotes.slice(1).map((x,i)=>x-targetNotes[i]),heardIntervals=heard.slice(1).map((x,i)=>x-heard[i]);const tolerance=singLevel===1?1.6:singLevel===2?1.35:1.15;const intervalErrors=wantIntervals.map((x,i)=>Math.abs(x-heardIntervals[i]));const intervalOk=intervalErrors.map(e=>e<=tolerance);const directions=wantIntervals.map((x,i)=>Math.sign(x)===Math.sign(heardIntervals[i]));const exact=intervalOk.filter(Boolean).length,dirOk=directions.filter(Boolean).length,total=n-1;const meanErr=intervalErrors.reduce((a,b)=>a+b,0)/total;const score=Math.max(0,Math.min(100,Math.round(100-meanErr*18)));$('#pitchLive').innerHTML=`Интервалы: <strong>${exact} из ${total}</strong> близко по величине · направление: <strong>${dirOk} из ${total}</strong>.`;
const cv=$('#contourView');if(cv){cv.classList.remove('hidden');cv.innerHTML=`<strong>Рисунок мелодии</strong><br><small>Образец</small><div style="font-size:28px;letter-spacing:8px">${arrows(wantIntervals)}</div><small>Ты спел(а)</small><div style="font-size:28px;letter-spacing:8px">${arrows(heardIntervals)}</div>`}
const ok=exact===total;const msg=ok?`Отлично! Ты сохранил(а) рисунок и интервалы мелодии — ${score}%.`:dirOk===total?`Контур верный. Теперь попробуй точнее расстояния между звуками — ${score}%.`:`Совпало направлений ${dirOk} из ${total}. Посмотри на стрелки и послушай мотив ещё раз.`;finishAttempt(ok,msg)}
function finishAttempt(ok,msg){count++;if(ok)correct++;$('#creativeCount').textContent=count;feedback(msg);$('#creativeActions').classList.remove('hidden');if(round>=5)$('#roundProgress').innerHTML=`<strong>Уровень завершён: ${correct} из 5</strong><br>${correct>=4?'Отличная работа. Можно переходить дальше.':correct>=3?'Хорошая основа. Можно повторить уровень или идти дальше.':'Лучше ещё немного поиграть на этом уровне.'}`}
function nextExercise(){if(round>=5){round=1;correct=0}else round++;targetRhythm=[];targetNotes=[];render();updateProgress();play(true)}
function retry(){render();play(false)}
function stopMic(){if(raf)cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
document.querySelectorAll('[data-creative]').forEach(b=>b.onclick=()=>open(b.dataset.creative));$('#creativeListen').onclick=()=>play(false);$('#creativeNext').onclick=nextExercise;$('#creativeRetry').onclick=retry;$('#creativeBack').onclick=()=>{stopMic();section.classList.add('hidden');$('#chooser').classList.remove('hidden')};
})();