(()=>{
const $=s=>document.querySelector(s);let ctx;
function audio(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(midi,d=.28,at=0){const c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+at;o.frequency.value=440*Math.pow(2,(midi-69)/12);o.type='sine';g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.2,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+d+.03)}
function seq(notes){notes.forEach((n,i)=>tone(n,.28,i*.45))}
const cards=$('#chooser');if(!cards)return;
const defs=[{id:'rhythm',icon:'🥁',title:'Ритмическое эхо',text:'Послушай короткий ритм и повтори его касаниями. Игра сравнит твой ритм с образцом.',action:'Слушать ритм'},{id:'sing',icon:'🎤',title:'Повтори мелодию голосом',text:'Послушай маленькую мелодию и спой её. Микрофон определит движение твоего голоса.',action:'Слушать мелодию'},{id:'continue',icon:'✨',title:'Продолжи музыкальную фразу',text:'Послушай начало и придумай собственное продолжение. Здесь нет неправильного ответа.',action:'Дай мне начало'}];
defs.forEach(d=>{const b=document.createElement('button');b.className='game-card creative-card';b.dataset.creative=d.id;b.innerHTML=`<span class="icon">${d.icon}</span><h2>${d.title}</h2><p>${d.text}</p><span class="go">Играть →</span>`;cards.appendChild(b)});
const section=document.createElement('section');section.id='creativeGame';section.className='game hidden';section.innerHTML=`<button class="back-games" id="creativeBack">← Все игры</button><div class="game-head"><div><div class="eyebrow">Творческая игра</div><h2 id="creativeTitle"></h2></div><div class="score"><strong id="creativeCount">0</strong><small>попыток</small></div></div><p class="muted" id="creativeText"></p><div class="play-zone"><button id="creativeListen" class="listen">▶<span id="creativeAction"></span></button></div><div id="creativeArea"></div><div id="creativeFeedback" class="feedback"></div><button id="creativeNext" class="primary hidden">Ещё раз</button>`;document.querySelector('.wrap').appendChild(section);
let mode='',count=0,targetRhythm=[],taps=[],tapStart=0,targetNotes=[],stream=null,raf=0;
function open(id){mode=id;count=0;$('#chooser').classList.add('hidden');document.querySelectorAll('.game').forEach(x=>x.classList.add('hidden'));section.classList.remove('hidden');const d=defs.find(x=>x.id===id);$('#creativeTitle').textContent=d.title;$('#creativeText').textContent=d.text;$('#creativeAction').textContent=d.action;$('#creativeCount').textContent='0';$('#creativeFeedback').textContent='';$('#creativeNext').classList.add('hidden');render()}
function render(){stopMic();const a=$('#creativeArea');if(mode==='rhythm')a.innerHTML='<button id="tapPad" class="tap-pad" type="button">ТАП<br><small>повтори ритм здесь</small></button><div id="tapDots" class="tap-dots"></div><button id="checkRhythm" class="primary" type="button">Проверить ритм</button>';else if(mode==='sing')a.innerHTML='<div class="creative-prompt">Сначала послушай мелодию. Затем нажми микрофон и пропой её без слов.</div><button id="startSing" class="primary creative-done" type="button">🎤 Начать петь</button><div id="pitchLive" class="feedback"></div>';else a.innerHTML='<div class="creative-prompt">После прослушивания придумай своё окончание фразы.</div><button id="didIt" class="primary creative-done" type="button">Я ответил(а) музыкой</button>';if($('#tapPad'))$('#tapPad').onclick=tap;if($('#checkRhythm'))$('#checkRhythm').onclick=scoreRhythm;if($('#startSing'))$('#startSing').onclick=startMic;if($('#didIt'))$('#didIt').onclick=done}
function tap(){const now=performance.now();if(!taps.length)tapStart=now;taps.push((now-tapStart)/1000);tone(60,.06);const dot=document.createElement('i');$('#tapDots').appendChild(dot)}
function scoreRhythm(){if(taps.length!==targetRhythm.length){feedback(`В образце ${targetRhythm.length} ударов, а у тебя ${taps.length}. Попробуй ещё раз.`);return}const ti=targetRhythm.slice(1).map((x,i)=>x-targetRhythm[i]),ui=taps.slice(1).map((x,i)=>x-taps[i]);const scale=ti.reduce((a,b)=>a+b,0)/Math.max(.01,ui.reduce((a,b)=>a+b,0));let err=0;ti.forEach((x,i)=>err+=Math.abs(x-ui[i]*scale)/x);err/=ti.length;const pct=Math.max(0,Math.round(100*(1-err)));count++;$('#creativeCount').textContent=count;feedback(pct>=85?`Отличное эхо — ${pct}% точности.`:pct>=65?`Очень близко — ${pct}%. Ещё раз и будет точнее.`:`Получилось ${pct}%. Послушай расстояние между ударами ещё раз.`);$('#creativeNext').classList.remove('hidden')}
function feedback(x){$('#creativeFeedback').innerHTML=`<strong>${x}</strong>`}
function play(){if(mode==='rhythm'){const patterns=[[0,.36,.72,1.25,1.61],[0,.48,.72,1.2,1.68],[0,.32,.82,1.14,1.64]];targetRhythm=patterns[Math.floor(Math.random()*patterns.length)];targetRhythm.forEach(t=>tone(48,.07,t));taps=[];$('#tapDots').innerHTML=''}else if(mode==='sing'){const base=60+Math.floor(Math.random()*4),shapes=[[0,2,4,2],[0,-2,-4,-2],[0,3,0,-2],[0,-2,1,4]];targetNotes=shapes[Math.floor(Math.random()*shapes.length)].map(x=>base+x);seq(targetNotes)}else{const base=60+Math.floor(Math.random()*4);seq([base,base+2,base+5])}}
function autoCorrelate(buf,sr){let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);if(rms<.015)return-1;let best=-1,bestCorr=0;for(let off=Math.floor(sr/900);off<Math.min(Math.floor(sr/80),buf.length/2);off++){let c=0;for(let i=0;i<buf.length-off;i++)c+=buf[i]*buf[i+off];if(c>bestCorr){bestCorr=c;best=off}}return best>0?sr/best:-1}
async function startMic(){try{stopMic();stream=await navigator.mediaDevices.getUserMedia({audio:true});const c=audio(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=2048;src.connect(an);const buf=new Float32Array(an.fftSize),samples=[],start=performance.now();$('#startSing').textContent='Слушаю…';function loop(){an.getFloatTimeDomainData(buf);const hz=autoCorrelate(buf,c.sampleRate);if(hz>70&&hz<1000)samples.push({t:performance.now()-start,m:69+12*Math.log2(hz/440)});if(performance.now()-start<4000){raf=requestAnimationFrame(loop);return}stopMic();analyseSong(samples)}loop()}catch(e){feedback('Не удалось включить микрофон. Разреши доступ к микрофону в браузере и попробуй снова.')}}
function analyseSong(s){if(s.length<8){feedback('Я почти не услышал устойчивый голос. Попробуй спеть чуть громче и протяжнее.');render();return}const dur=s[s.length-1].t,parts=[0,1,2,3].map(k=>s.filter(x=>x.t>=dur*k/4&&x.t<dur*(k+1)/4).map(x=>x.m)).map(a=>a.length?a.sort((x,y)=>x-y)[Math.floor(a.length/2)]:null);if(parts.some(x=>x==null)){feedback('Не все четыре звука удалось услышать. Попробуй ещё раз.');render();return}const rel=a=>a.slice(1).map((x,i)=>Math.sign(Math.round((x-a[i])*2)/2));const want=rel(targetNotes),got=rel(parts);let ok=0;want.forEach((x,i)=>{if(x===got[i])ok++});count++;$('#creativeCount').textContent=count;feedback(ok===3?'Ты точно повторил(а) направление мелодии — 3 из 3 движений!':`Я услышал ${ok} из 3 движений мелодии. Попробуй ещё раз.`);$('#pitchLive').textContent=`Услышано примерно: ${parts.map(x=>Math.round(x)).join(' · ')}`;$('#creativeNext').classList.remove('hidden')}
function stopMic(){if(raf)cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function done(){count++;$('#creativeCount').textContent=count;feedback('Твой вариант существует только у тебя. Повтори его или придумай другой.');$('#creativeNext').classList.remove('hidden')}
document.querySelectorAll('[data-creative]').forEach(b=>b.onclick=()=>open(b.dataset.creative));$('#creativeListen').onclick=play;$('#creativeNext').onclick=()=>{render();$('#creativeFeedback').textContent='';$('#creativeNext').classList.add('hidden');play()};$('#creativeBack').onclick=()=>{stopMic();section.classList.add('hidden');$('#chooser').classList.remove('hidden')};
})();