import './voice-cards.js';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const s=createClient('https://uecdlqlwsrqmocbpgiwj.supabase.co','sb_publishable_QJ_4e8-BHl0gOZifGqdv1w_doFwpTlb',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);const emotions=['спокойно','тревожно','радостно','грустно','злюсь','устала/устал','растерянно','интерес','напряжение','легкость'];
let selectedBefore=new Set(),selectedAfter=new Set(),mode=null,effect=null,mediaBlob=null,mediaType=null,recorder=null,stream=null,timerId=null,seconds=0;
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)};
function chips(el,set){el.replaceChildren();emotions.forEach(x=>{const b=document.createElement('button');b.type='button';b.className='chip';b.textContent=x;b.onclick=()=>{set.has(x)?set.delete(x):set.add(x);b.classList.toggle('on',set.has(x))};el.appendChild(b)})}
chips($('beforeChips'),selectedBefore);chips($('afterChips'),selectedAfter);
$('beforeIntensity').oninput=e=>$('beforeVal').textContent=e.target.value;$('afterIntensity').oninput=e=>$('afterVal').textContent=e.target.value;
async function event(name,extra={}){const {data:{user}}=await s.auth.getUser();if(!user)return;const safe={};if(extra.duration_sec!=null)safe.duration_sec=extra.duration_sec;if(extra.completed!=null)safe.completed=extra.completed;await s.from('usage_events').insert({user_id:user.id,event_name:name,modality:extra.modality||null,metadata:safe})}
async function authState(){const {data:{user}}=await s.auth.getUser();$('authView').classList.toggle('hidden',!!user);$('appView').classList.toggle('hidden',!user);$('logoutBtn').classList.toggle('hidden',!user);if(user){event('app_open');loadHistory()}}
$('signupBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!$('acceptTerms').checked){$('authMsg').textContent='Чтобы создать аккаунт, нужно принять Политику конфиденциальности и Условия.';return}if(password.length<8){$('authMsg').textContent='Пароль должен быть не короче 8 символов.';return}$('signupBtn').disabled=true;const {data,error}=await s.auth.signUp({email,password,options:{data:{privacy_accepted:true,terms_accepted:true,privacy_version:'2026-08-29',terms_version:'2026-08-29',marketing_consent:$('marketingConsent').checked,research_consent:$('researchConsent').checked}}});$('signupBtn').disabled=false;if(error){$('authMsg').textContent=error.message;return}$('authMsg').textContent=data.session?'Аккаунт создан.':'Аккаунт создан. Если включено подтверждение email, проверьте почту.';authState()};
$('loginBtn').onclick=async()=>{const {error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'';if(!error)authState()};
$('logoutBtn').onclick=async()=>{await s.auth.signOut();location.reload()};
s.auth.onAuthStateChange(()=>setTimeout(authState,0));authState();
function showMode(m){mode=m;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));['voice','movement','drawing','text'].forEach(x=>$(x+'Panel').classList.toggle('hidden',x!==m));$('afterBlock').classList.remove('hidden');mediaBlob=null;mediaType=null;event('modality_selected',{modality:m})}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>showMode(b.dataset.mode));
function bestMime(kind){const tests=kind==='video'?['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm']:['audio/webm;codecs=opus','audio/webm'];return tests.find(x=>MediaRecorder.isTypeSupported?.(x))||''}
function tick(el){seconds=0;el.textContent='00:00';clearInterval(timerId);timerId=setInterval(()=>{seconds++;el.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')},1000)}
async function startVoice(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];const mime=bestMime('audio');recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{mediaBlob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});mediaType='audio';$('voicePreview').src=URL.createObjectURL(mediaBlob);$('voicePreview').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());clearInterval(timerId);$('voiceRecord').classList.remove('recording');$('voiceRecord').innerHTML='🎙<br>Записать заново';$('voiceStatus').textContent='Запись готова'};recorder.start();tick($('voiceTimer'));$('voiceRecord').classList.add('recording');$('voiceRecord').innerHTML='■<br>Остановить';$('voiceStatus').textContent='Идёт запись'}catch(e){$('voiceStatus').textContent='Не удалось включить микрофон. Проверьте разрешение браузера.'}}
$('voiceRecord').onclick=()=>recorder?.state==='recording'?recorder.stop():startVoice();
async function startMovement(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});const chunks=[];const mime=bestMime('video');recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{mediaBlob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});mediaType='video';$('movementPreview').src=URL.createObjectURL(mediaBlob);$('movementPreview').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());$('movementRecord').textContent='Записать движение заново';$('movementStatus').textContent='Запись готова'};recorder.start();$('movementRecord').textContent='Остановить запись';$('movementStatus').textContent='Идёт запись'}catch(e){$('movementStatus').textContent='Не удалось включить камеру/микрофон. Проверьте разрешения браузера.'}}
$('movementRecord').onclick=()=>recorder?.state==='recording'?(recorder.stop()):startMovement();
const c=$('drawCanvas'),ctx=c.getContext('2d');ctx.lineWidth=10;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#8f5961';let drawing=false;document.querySelectorAll('#drawPalette .swatch').forEach(b=>b.onclick=()=>{ctx.strokeStyle=b.dataset.color;document.querySelectorAll('#drawPalette .swatch').forEach(x=>x.classList.toggle('on',x===b))});function pos(e){const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}}function begin(e){drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){drawing=false}c.addEventListener('pointerdown',begin);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end);$('clearCanvas').onclick=()=>ctx.clearRect(0,0,c.width,c.height);
document.querySelectorAll('.effect').forEach(b=>b.onclick=()=>{effect=b.dataset.effect;document.querySelectorAll('.effect').forEach(x=>x.classList.toggle('on',x===b))});
async function canvasBlob(){return new Promise(res=>c.toBlob(res,'image/png'))}
async function upload(user,id,blob){if(!blob)return null;let ext='webm';if(blob.type.includes('png'))ext='png';else if(blob.type.includes('mp4'))ext='mp4';const path=`${user.id}/${id}/expression.${ext}`;const {error}=await s.storage.from('voice-recordings').upload(path,blob,{contentType:blob.type||'application/octet-stream',upsert:false});if(error)throw error;return path}
$('saveEntry').onclick=async()=>{if(!mode){toast('Сначала выберите способ выражения');return}if(!effect){toast('Отметьте, как вам после практики');return}const {data:{user}}=await s.auth.getUser();if(!user)return;let blob=mediaBlob;if(mode==='drawing')blob=await canvasBlob();const text=mode==='text'?$('expressionText').value.trim():null;if(mode==='voice'&&!blob){toast('Сначала запишите голос');return}if(mode==='movement'&&!blob){toast('Сначала запишите движение');return}if(mode==='text'&&!text){toast('Напишите хотя бы несколько слов');return}$('saveEntry').disabled=true;$('saveStatus').textContent='Сохраняю…';try{const payload={user_id:user.id,title:'Мой след',modality:mode,intensity_before:+$('beforeIntensity').value,intensity_after:+$('afterIntensity').value,effect_self_report:effect,emotions_before:[...selectedBefore],emotions_after:[...selectedAfter],state_custom_before:$('beforeCustom').value.trim()||null,state_custom_after:$('afterCustom').value.trim()||null,reflection_text:$('reflection').value.trim()||null,expression_text:text,completed:true,duration_before:seconds||null};const {data:row,error}=await s.from('voice_entries').insert(payload).select().single();if(error)throw error;if(blob){const path=await upload(user,row.id,blob);const patch={expression_media_path:path};if(mode==='voice')patch.audio_path_before=path;if(mode==='drawing')patch.drawing_before_path=path;if(mode==='movement')patch.state_video_before_path=path;const {error:uerr}=await s.from('voice_entries').update(patch).eq('id',row.id);if(uerr)throw uerr}await event('practice_completed',{modality:mode,duration_sec:seconds||0,completed:true});toast('Сохранено в ваш дневник');reset();loadHistory();showView('history')}catch(e){$('saveStatus').textContent='Не удалось сохранить: '+e.message}finally{$('saveEntry').disabled=false}};
function reset(){selectedBefore=new Set();selectedAfter=new Set();chips($('beforeChips'),selectedBefore);chips($('afterChips'),selectedAfter);$('beforeCustom').value='';$('afterCustom').value='';$('expressionText').value='';$('reflection').value='';$('beforeIntensity').value=5;$('afterIntensity').value=5;$('beforeVal').textContent=5;$('afterVal').textContent=5;effect=null;mode=null;mediaBlob=null;seconds=0;document.querySelectorAll('.mode,.effect').forEach(x=>x.classList.remove('on'));['voice','movement','drawing','text'].forEach(x=>$(x+'Panel').classList.add('hidden'));$('afterBlock').classList.add('hidden');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#8f5961';document.querySelectorAll('#drawPalette .swatch').forEach((x,i)=>x.classList.toggle('on',i===0));$('voicePreview').classList.add('hidden');$('movementPreview').classList.add('hidden');$('saveStatus').textContent=''}
const labels={voice:'Голос',movement:'Движение',drawing:'Рисунок',text:'Текст'};const effects={much_lighter:'намного легче',lighter:'немного легче',same:'примерно так же',heavier:'немного тяжелее',much_heavier:'намного тяжелее'};
async function signed(path){if(!path)return null;const {data}=await s.storage.from('voice-recordings').createSignedUrl(path,1800);return data?.signedUrl||null}
async function loadHistory(){const {data,error}=await s.from('voice_entries').select('*').order('created_at',{ascending:false}).limit(60);if(error)return;const list=data||[];const last30=list.filter(x=>Date.now()-new Date(x.created_at).getTime()<30*86400000);const helpful=last30.filter(x=>['lighter','much_lighter'].includes(x.effect_self_report)).length;const modeCounts={};last30.forEach(x=>{const m=x.modality||(x.audio_path_before?'voice':null);if(m)modeCounts[m]=(modeCounts[m]||0)+1});const fav=Object.entries(modeCounts).sort((a,b)=>b[1]-a[1])[0]?.[0];$('stats').replaceChildren();[['Практик за 30 дней',last30.length],['Стало легче',last30.length?Math.round(helpful/last30.length*100)+'%':'—'],['Чаще выбираю',fav?labels[fav]:'—'],['Всего записей',list.length]].forEach(([k,v])=>{const d=document.createElement('div');d.className='stat';const b=document.createElement('b');b.textContent=v;const span=document.createElement('span');span.textContent=k;d.append(b,span);$('stats').appendChild(d)});$('entries').replaceChildren();if(!list.length){$('entries').textContent='Здесь появятся ваши первые записи.';return}for(const e of list){const d=document.createElement('div');d.className='entry';const head=document.createElement('div');head.className='entryhead';const title=document.createElement('div');title.className='entrytitle';const m=e.modality||(e.audio_path_before?'voice':null);title.textContent=labels[m]||'Практика';const date=document.createElement('div');date.className='date';date.textContent=new Date(e.created_at).toLocaleDateString('ru-RU',{day:'numeric',month:'short',year:'numeric'});head.append(title,date);d.appendChild(head);if(e.intensity_before!=null&&e.intensity_after!=null){const p=document.createElement('span');p.className='pill';p.textContent=`интенсивность ${e.intensity_before} → ${e.intensity_after}`;d.appendChild(p)}if(e.effect_self_report){const p=document.createElement('span');p.className='pill';p.textContent=effects[e.effect_self_report]||e.effect_self_report;d.appendChild(p)}if(e.expression_text){const p=document.createElement('p');p.textContent=e.expression_text;d.appendChild(p)}if(e.reflection_text){const p=document.createElement('p');p.className='small';p.textContent='Заметила/заметил: '+e.reflection_text;d.appendChild(p)}const path=e.expression_media_path||e.audio_path_before||e.drawing_before_path||e.state_video_before_path;if(path){const url=await signed(path);if(url){if(m==='voice'){const a=document.createElement('audio');a.controls=true;a.src=url;d.appendChild(a)}else if(m==='movement'){const v=document.createElement('video');v.controls=true;v.playsInline=true;v.src=url;d.appendChild(v)}else if(m==='drawing'){const im=document.createElement('img');im.src=url;im.alt='Мой рисунок';im.style='width:100%;margin-top:10px;border-radius:16px;border:1px solid #e4d9d1';d.appendChild(im)}}}$('entries').appendChild(d)}}
function showView(v){$('practiceView').classList.toggle('hidden',v!=='practice');$('historyView').classList.toggle('hidden',v!=='history');$('aboutView').classList.toggle('hidden',v!=='about');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.view===v));if(v==='history')loadHistory();window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));