import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const s=createClient('https://uecdlqlwsrqmocbpgiwj.supabase.co','sb_publishable_QJ_4e8-BHl0gOZifGqdv1w_doFwpTlb',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let currentUser=null;let audioFile=null;let coverBlob=null;let recorder=null;let stream=null;let timerId=null;let seconds=0;let coverVariant=0;let imageStyle='cinematic';
const publicUrl=p=>s.storage.from('improvisation-gallery').getPublicUrl(p).data.publicUrl;
async function loadGallery(){const {data,error}=await s.from('improvisation_gallery').select('*').eq('is_published',true).eq('consent_to_publish',true).order('published_at',{ascending:false});const g=$('gallery');g.replaceChildren();if(error||!data?.length){const e=document.createElement('div');e.className='empty';e.textContent='Пока здесь тихо. Первая работа скоро появится.';g.append(e);return}for(const x of data){const card=document.createElement('article');card.className='piece';if(x.image_path){const im=document.createElement('img');im.src=publicUrl(x.image_path);im.alt=x.title;card.append(im)}const c=document.createElement('div');c.className='copy';const h=document.createElement('h3');h.textContent=x.title;const by=document.createElement('div');by.className='by';by.textContent=x.performer_name?`Импровизация: ${x.performer_name}`:'Импровизация';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=publicUrl(x.audio_path);c.append(h,by,a);if(x.description){const p=document.createElement('p');p.className='small';p.textContent=x.description;c.append(p)}card.append(c);g.append(card)}}
async function authState(){const {data:{user}}=await s.auth.getUser();currentUser=user;$('authBox').classList.toggle('hidden',!!user);$('editor').classList.toggle('hidden',!user)}
$('login').onclick=async()=>{const {error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'';if(!error)authState()};
$('signup').onclick=async()=>{const {error}=await s.auth.signUp({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'Аккаунт создан. Если требуется подтверждение email — проверьте почту.';if(!error)authState()};
$('logout').onclick=async()=>{await s.auth.signOut();authState()};s.auth.onAuthStateChange(()=>setTimeout(authState,0));
const starts=['Там, где','После','Между','Пока звучит','Когда приходит','Внутри'];const nouns=['тишина','воздух','свет','волна','дорога','эхо','пульс','туман','огонь','поворот','дыхание','пространство'];
const surpriseThemes=['город, который просыпается под водой','огромная красная птица над зимним лесом','лестница из облаков в ночное небо','маленький дом внутри прозрачного кита','сад, где вместо цветов растут колокольчики','поезд, едущий через море звёзд','разговор луны и старого дерева','ветер, который собирает потерянные мелодии','комната, заполненная золотым дождём','две планеты, соединённые тонкой нитью','танец теней на стенах древнего города','дорога из света посреди тёмного океана'];
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function rand(seed,n){return ((Math.sin(seed*12.9898+n*78.233)*43758.5453)%1+1)%1}
document.querySelectorAll('.style').forEach(b=>b.onclick=()=>{imageStyle=b.dataset.style;document.querySelectorAll('.style').forEach(x=>x.classList.toggle('on',x===b))});
$('surpriseTheme').onclick=()=>{const idx=Math.floor(Math.random()*surpriseThemes.length);$('theme').value=surpriseThemes[idx];coverVariant=0;generateThemeCover()};
async function putImageOnCanvas(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const canvas=$('cover'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const scale=Math.max(canvas.width/img.width,canvas.height/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);canvas.toBlob(b=>{coverBlob=b;resolve()},'image/png',.95)};img.onerror=reject;img.src=src})}
async function generateThemeCover(){const topic=$('theme').value.trim();if(!topic){$('imageStatus').textContent='Напиши тему — или нажми «Удиви меня».';return}const btn=$('makeThemeCover'),again=$('remakeThemeCover');btn.disabled=true;again.disabled=true;coverBlob=null;$('imageStatus').textContent='Создаю образ… это может занять немного времени.';try{const r=await fetch('/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:`${topic}${coverVariant?` — alternative interpretation ${coverVariant+1}`:''}`,style:imageStyle})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Не удалось создать картинку.');const src=data.image||data.url;if(!src)throw new Error('Генератор не вернул изображение.');await putImageOnCanvas(src);$('imageStatus').textContent='Картинка готова. Посмотри на неё несколько секунд — и можно начинать импровизацию.';$('saveMsg').textContent=''}catch(e){$('imageStatus').textContent='Не получилось: '+e.message}finally{btn.disabled=false;again.disabled=false}}
$('makeThemeCover').onclick=()=>{coverVariant=0;generateThemeCover()};$('remakeThemeCover').onclick=()=>{coverVariant++;generateThemeCover()};
$('makeTitle').onclick=()=>{const raw=[$('theme').value.trim(),$('words').value.trim()].filter(Boolean).join(', ');const parts=raw.split(/[,;]+/).map(x=>x.trim()).filter(Boolean);const seed=hash(raw||Date.now().toString());let t;if(parts.length>=2)t=`${parts[0][0].toUpperCase()+parts[0].slice(1)} и ${parts[1]}`;else t=`${starts[Math.floor(rand(seed,1)*starts.length)]} ${nouns[Math.floor(rand(seed,2)*nouns.length)]}`;$('title').value=t};
$('audio').onchange=e=>{audioFile=e.target.files?.[0]||null;if(audioFile){$('recordPreview').src=URL.createObjectURL(audioFile);$('recordPreview').classList.remove('hidden');$('recordStatus').textContent='Готовая запись выбрана.'}};
function bestMime(){const tests=['audio/webm;codecs=opus','audio/webm','audio/mp4'];return tests.find(x=>MediaRecorder.isTypeSupported?.(x))||''}function showTimer(){seconds=0;$('recordTimer').textContent='00:00';clearInterval(timerId);timerId=setInterval(()=>{seconds++;$('recordTimer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')},1000)}
async function startRecording(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[],mime=bestMime();recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{audioFile=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});$('recordPreview').src=URL.createObjectURL(audioFile);$('recordPreview').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());clearInterval(timerId);$('recordAudio').classList.remove('recording');$('recordAudio').querySelector('span').textContent='Записать заново';$('recordStatus').textContent='Запись готова. Можно прослушать и сохранить.'};recorder.start();showTimer();$('recordAudio').classList.add('recording');$('recordAudio').querySelector('span').textContent='Остановить запись';$('recordStatus').textContent=coverBlob?'Импровизация на картинку записывается…':'Свободная импровизация записывается…'}catch(e){$('recordStatus').textContent='Не удалось включить микрофон. Проверь разрешение браузера.'}}
$('recordAudio').onclick=()=>recorder?.state==='recording'?recorder.stop():startRecording();
async function upload(path,file){const {error}=await s.storage.from('improvisation-gallery').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error}
$('save').onclick=async()=>{if(!currentUser){$('saveMsg').textContent='Сначала войдите.';return}if(!audioFile){$('saveMsg').textContent='Запишите или загрузите импровизацию.';return}if(!$('title').value.trim())$('makeTitle').click();if(!$('consent').checked&&$('publish').checked){$('saveMsg').textContent='Для публикации нужно подтвердить согласие исполнителя.';return}$('save').disabled=true;$('saveMsg').textContent='Сохраняю…';try{const id=crypto.randomUUID();let ext='webm';if(audioFile instanceof File&&audioFile.name.includes('.'))ext=(audioFile.name.split('.').pop()||'webm').toLowerCase();else if(audioFile.type.includes('mp4'))ext='m4a';const audioPath=`${currentUser.id}/${id}/audio.${ext}`;const imagePath=coverBlob?`${currentUser.id}/${id}/cover.png`:null;await upload(audioPath,audioFile);if(coverBlob)await upload(imagePath,coverBlob);const publish=$('publish').checked&&$('consent').checked;const description=[$('theme').value.trim(),$('words').value.trim()].filter(Boolean).join(' · ')||null;const {error}=await s.from('improvisation_gallery').insert({id,user_id:currentUser.id,performer_name:$('performer').value.trim()||null,title:$('title').value.trim(),description,audio_path:audioPath,image_path:imagePath,visual_seed:coverBlob?`ai:${imageStyle}:${hash(($('theme').value||'')+'|'+coverVariant)}`:null,consent_to_publish:$('consent').checked,is_published:publish,published_at:publish?new Date().toISOString():null});if(error)throw error;$('saveMsg').textContent=publish?'Работа опубликована в галерее.':'Работа сохранена без публикации.';['performer','words','title','theme'].forEach(id=>$(id).value='');$('audio').value='';$('consent').checked=false;$('publish').checked=false;audioFile=null;coverBlob=null;coverVariant=0;$('recordPreview').classList.add('hidden');$('recordPreview').removeAttribute('src');$('recordTimer').textContent='00:00';$('recordStatus').textContent='Можно записать свободную импровизацию — картинка не обязательна.';$('imageStatus').textContent='';const ctx=$('cover').getContext('2d');ctx.clearRect(0,0,900,900);loadGallery()}catch(e){$('saveMsg').textContent='Не удалось сохранить: '+e.message}finally{$('save').disabled=false}};
loadGallery();authState();