import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const s=createClient('https://uecdlqlwsrqmocbpgiwj.supabase.co','sb_publishable_QJ_4e8-BHl0gOZifGqdv1w_doFwpTlb',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let currentUser=null;let audioFile=null;let coverBlob=null;
const publicUrl=p=>s.storage.from('improvisation-gallery').getPublicUrl(p).data.publicUrl;
async function loadGallery(){const {data,error}=await s.from('improvisation_gallery').select('*').eq('is_published',true).eq('consent_to_publish',true).order('published_at',{ascending:false});const g=$('gallery');g.replaceChildren();if(error||!data?.length){const e=document.createElement('div');e.className='empty';e.textContent='Пока здесь тихо. Первая работа скоро появится.';g.append(e);return}for(const x of data){const card=document.createElement('article');card.className='piece';if(x.image_path){const im=document.createElement('img');im.src=publicUrl(x.image_path);im.alt=x.title;card.append(im)}const c=document.createElement('div');c.className='copy';const h=document.createElement('h3');h.textContent=x.title;const by=document.createElement('div');by.className='by';by.textContent=x.performer_name?`Импровизация: ${x.performer_name}`:'Импровизация';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=publicUrl(x.audio_path);c.append(h,by,a);if(x.description){const p=document.createElement('p');p.className='small';p.textContent=x.description;c.append(p)}card.append(c);g.append(card)}}
async function authState(){const {data:{user}}=await s.auth.getUser();currentUser=user;$('authBox').classList.toggle('hidden',!!user);$('editor').classList.toggle('hidden',!user)}
$('login').onclick=async()=>{const {error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'';if(!error)authState()};
$('signup').onclick=async()=>{const {error}=await s.auth.signUp({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'Аккаунт создан. Если требуется подтверждение email — проверьте почту.';if(!error)authState()};
$('logout').onclick=async()=>{await s.auth.signOut();authState()};
s.auth.onAuthStateChange(()=>setTimeout(authState,0));
const starts=['Там, где','После','Между','Пока звучит','Когда приходит','Внутри'];const nouns=['тишина','воздух','свет','волна','дорога','эхо','пульс','туман','огонь','поворот','дыхание','пространство'];
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function rand(seed,n){return ((Math.sin(seed*12.9898+n*78.233)*43758.5453)%1+1)%1}
$('makeTitle').onclick=()=>{const raw=$('words').value.trim();const parts=raw.split(/[,;]+/).map(x=>x.trim()).filter(Boolean);const seed=hash(raw||Date.now().toString());let t;if(parts.length>=2)t=`${parts[0][0].toUpperCase()+parts[0].slice(1)} и ${parts[1]}`;else t=`${starts[Math.floor(rand(seed,1)*starts.length)]} ${nouns[Math.floor(rand(seed,2)*nouns.length)]}`;$('title').value=t};
$('audio').onchange=e=>{audioFile=e.target.files?.[0]||null;coverBlob=null};
async function audioFeatures(file){const buf=await file.arrayBuffer();const ac=new (window.AudioContext||window.webkitAudioContext)();const decoded=await ac.decodeAudioData(buf.slice(0));const ch=decoded.getChannelData(0);const buckets=48,step=Math.max(1,Math.floor(ch.length/buckets));const vals=[];for(let i=0;i<buckets;i++){let sum=0,c=0;for(let j=i*step;j<Math.min(ch.length,(i+1)*step);j+=Math.max(1,Math.floor(step/200))){sum+=Math.abs(ch[j]);c++}vals.push(c?sum/c:0)}ac.close();return vals}
async function drawCover(){if(!audioFile){$('saveMsg').textContent='Сначала выберите аудиозапись.';return}const vals=await audioFeatures(audioFile);const canvas=$('cover'),ctx=canvas.getContext('2d');const seed=hash(audioFile.name+$('words').value+$('performer').value);const hue=Math.floor(rand(seed,1)*360);const hue2=(hue+70+Math.floor(rand(seed,2)*90))%360;const grad=ctx.createLinearGradient(0,0,900,900);grad.addColorStop(0,`hsl(${hue} 34% 88%)`);grad.addColorStop(1,`hsl(${hue2} 38% 72%)`);ctx.fillStyle=grad;ctx.fillRect(0,0,900,900);ctx.globalAlpha=.75;for(let i=0;i<vals.length;i++){const a=Math.min(1,vals[i]*8+.05),x=(i+.5)*900/vals.length,y=450+Math.sin(i*.65+seed%7)*80;ctx.beginPath();ctx.fillStyle=`hsla(${(hue+i*4)%360} 55% ${35+Math.floor(rand(seed,i)*30)}% / ${.22+a*.55})`;ctx.arc(x,y,18+a*150,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='700 42px -apple-system,system-ui,sans-serif';ctx.textAlign='left';ctx.fillText(($('title').value||'Импровизация').slice(0,30),54,820);coverBlob=await new Promise(r=>canvas.toBlob(r,'image/png',.92));$('saveMsg').textContent='Обложка готова.'}
$('makeCover').onclick=drawCover;
async function upload(path,file){const {error}=await s.storage.from('improvisation-gallery').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error}
$('save').onclick=async()=>{if(!currentUser){$('saveMsg').textContent='Сначала войдите.';return}if(!audioFile){$('saveMsg').textContent='Добавьте аудиозапись.';return}if(!$('title').value.trim())$('makeTitle').click();if(!$('consent').checked&&$('publish').checked){$('saveMsg').textContent='Для публикации нужно подтвердить согласие исполнителя.';return}$('save').disabled=true;$('saveMsg').textContent='Сохраняю…';try{if(!coverBlob)await drawCover();const id=crypto.randomUUID();const ext=(audioFile.name.split('.').pop()||'webm').toLowerCase();const audioPath=`${currentUser.id}/${id}/audio.${ext}`;const imagePath=`${currentUser.id}/${id}/cover.png`;await upload(audioPath,audioFile);if(coverBlob)await upload(imagePath,coverBlob);const publish=$('publish').checked&&$('consent').checked;const {error}=await s.from('improvisation_gallery').insert({id,user_id:currentUser.id,performer_name:$('performer').value.trim()||null,title:$('title').value.trim(),description:$('words').value.trim()||null,audio_path:audioPath,image_path:coverBlob?imagePath:null,visual_seed:String(hash(audioFile.name+$('words').value)),consent_to_publish:$('consent').checked,is_published:publish,published_at:publish?new Date().toISOString():null});if(error)throw error;$('saveMsg').textContent=publish?'Работа опубликована в галерее.':'Работа сохранена без публикации.';$('performer').value='';$('words').value='';$('title').value='';$('audio').value='';$('consent').checked=false;$('publish').checked=false;audioFile=null;coverBlob=null;loadGallery()}catch(e){$('saveMsg').textContent='Не удалось сохранить: '+e.message}finally{$('save').disabled=false}};
loadGallery();authState();