const GAME_I18N={
 ru:{backHome:'← На главную',lab:'Музыкальная лаборатория',heroEyebrow:'Слушай · узнавай · играй',heroTitle:'Музыкальные игры',heroText:'Короткие тренажёры для развития слуха и музыкальной памяти. Можно играть на телефоне, планшете или компьютере.',pitchTitle:'Звуковысотное движение',pitchCard:'Определи на слух: звук идёт вверх, вниз или остаётся на месте.',quizTitle:'Угадай композитора',quizCard:'Послушай настоящий фрагмент произведения и выбери автора.',play:'Играть →',allGames:'← Все игры',game1:'Игра 1',game2:'Игра 2 · реальные записи',points:'очков',level:'Уровень:',listen:'Слушать',pitchPrompt:'Куда движется звук?',up:'Вверх',same:'На месте',down:'Вниз',next:'Следующий вопрос',listenExcerpt:'Слушать фрагмент',who:'Кто написал эту музыку?',correct:'Верно!',correctAnswer:'Правильный ответ',done:'Готово!',pitchGreat:'Отличный слух!',pitchGood:'Очень хорошо. Ещё один круг — и будет ещё увереннее.',pitchRetry:'Попробуй ещё раз и слушай расстояние между звуками.',quizGreat:'Блестяще!',quizGood:'Очень хороший результат.',quizRetry:'Ещё один круг поможет запомнить музыкальные портреты композиторов.',audioFail:'Не удалось запустить запись. Нажми «Слушать фрагмент» ещё раз.',loadFail:'Не удалось загрузить запись. Проверь интернет и попробуй ещё раз.',levels:['','Знакомство: 8 разных композиторов и самые узнаваемые темы, 3 варианта ответа, 15 секунд.','Начинающий: ещё больше произведений и композиторов, 4 варианта, 12 секунд.','Продвинутый: менее очевидные произведения, 4 варианта, 9 секунд.','Эксперт: весь каталог и короткий фрагмент — 6 секунд.']},
 en:{backHome:'← Home',lab:'Music Lab',heroEyebrow:'Listen · recognize · play',heroTitle:'Music Games',heroText:'Short activities for ear training and musical memory. Play on a phone, tablet, or computer.',pitchTitle:'Pitch Direction',pitchCard:'Listen and decide: does the sound go up, down, or stay the same?',quizTitle:'Guess the Composer',quizCard:'Listen to a real recording excerpt and choose the composer.',play:'Play →',allGames:'← All games',game1:'Game 1',game2:'Game 2 · real recordings',points:'points',level:'Level:',listen:'Listen',pitchPrompt:'Which way does the sound move?',up:'Up',same:'Same',down:'Down',next:'Next question',listenExcerpt:'Listen to excerpt',who:'Who composed this music?',correct:'Correct!',correctAnswer:'Correct answer',done:'Done!',pitchGreat:'Excellent ear!',pitchGood:'Very good. One more round will make it even more secure.',pitchRetry:'Try again and listen to the distance between the notes.',quizGreat:'Brilliant!',quizGood:'Very good result.',quizRetry:'Another round will help you remember the composers’ musical portraits.',audioFail:'Could not start the recording. Tap “Listen to excerpt” again.',loadFail:'Could not load the recording. Check your internet connection and try again.',levels:['','Introduction: 8 different composers, iconic themes, 3 choices, 15 seconds.','Beginner: more works and composers, 4 choices, 12 seconds.','Advanced: less obvious works, 4 choices, 9 seconds.','Expert: the full catalogue and only 6 seconds of music.']},
 he:{backHome:'→ לדף הבית',lab:'מעבדת מוזיקה',heroEyebrow:'להקשיב · לזהות · לשחק',heroTitle:'משחקי מוזיקה',heroText:'תרגילים קצרים לפיתוח השמיעה והזיכרון המוזיקלי. אפשר לשחק בטלפון, בטאבלט או במחשב.',pitchTitle:'כיוון הצליל',pitchCard:'הקשיבו וקבעו: האם הצליל עולה, יורד או נשאר במקום?',quizTitle:'מי המלחין?',quizCard:'הקשיבו לקטע מהקלטה אמיתית ובחרו את המלחין.',play:'לשחק ←',allGames:'→ כל המשחקים',game1:'משחק 1',game2:'משחק 2 · הקלטות אמיתיות',points:'נקודות',level:'רמה:',listen:'להקשיב',pitchPrompt:'לאיזה כיוון הצליל נע?',up:'למעלה',same:'נשאר',down:'למטה',next:'השאלה הבאה',listenExcerpt:'להקשיב לקטע',who:'מי הלחין את המוזיקה?',correct:'נכון!',correctAnswer:'התשובה הנכונה',done:'סיימנו!',pitchGreat:'שמיעה מצוינת!',pitchGood:'טוב מאוד. עוד סבב אחד ויהיה אפילו בטוח יותר.',pitchRetry:'נסו שוב והקשיבו למרחק בין הצלילים.',quizGreat:'מצוין!',quizGood:'תוצאה טובה מאוד.',quizRetry:'עוד סבב יעזור לזכור את הדמויות המוזיקליות של המלחינים.',audioFail:'לא ניתן להפעיל את ההקלטה. לחצו שוב על „להקשיב לקטע”.',loadFail:'לא ניתן לטעון את ההקלטה. בדקו את החיבור לאינטרנט ונסו שוב.',levels:['','היכרות: 8 מלחינים שונים, נושאים מוכרים מאוד, 3 תשובות ו־15 שניות.','מתחילים: יותר יצירות ומלחינים, 4 תשובות ו־12 שניות.','מתקדמים: יצירות פחות ברורות, 4 תשובות ו־9 שניות.','מומחים: כל המאגר ורק 6 שניות של מוזיקה.']}
};
const COMPOSER_I18N={
 'Людвиг ван Бетховен':{en:'Ludwig van Beethoven',he:'לודוויג ואן בטהובן'},'Эдвард Григ':{en:'Edvard Grieg',he:'אדוורד גריג'},'Вольфганг Амадей Моцарт':{en:'Wolfgang Amadeus Mozart',he:'וולפגנג אמדאוס מוצרט'},'Пётр Чайковский':{en:'Pyotr Tchaikovsky',he:'פיוטר צ׳ייקובסקי'},'Антонио Вивальди':{en:'Antonio Vivaldi',he:'אנטוניו ויוואלדי'},'Иоганн Себастьян Бах':{en:'Johann Sebastian Bach',he:'יוהאן סבסטיאן באך'},'Антонин Дворжак':{en:'Antonín Dvořák',he:'אנטונין דבוז׳אק'},'Бедржих Сметана':{en:'Bedřich Smetana',he:'בדז׳יך סמטנה'},'Феликс Мендельсон':{en:'Felix Mendelssohn',he:'פליקס מנדלסון'},'Фредерик Шопен':{en:'Frédéric Chopin',he:'פרדריק שופן'},'Иоганнес Брамс':{en:'Johannes Brahms',he:'יוהנס ברהמס'},'Александр Бородин':{en:'Alexander Borodin',he:'אלכסנדר בורודין'}
};
const WORK_I18N={
 beethoven5:{en:'Symphony No. 5',he:'סימפוניה מס׳ 5'},'grieg-mountain':{en:'In the Hall of the Mountain King',he:'במערת מלך ההר'},'mozart-k525':{en:'Eine kleine Nachtmusik — Minuet',he:'מוזיקת לילה זעירה — מינואט'},'tchaikovsky-swan':{en:'Swan Lake',he:'אגם הברבורים'},'vivaldi-spring':{en:'The Four Seasons — Spring',he:'ארבע העונות — אביב'},'bach-joy':{en:'Jesu, Joy of Man’s Desiring',he:'ישו, משאת נפש האדם'},'dvorak-newworld':{en:'Symphony No. 9 “From the New World” — IV',he:'סימפוניה מס׳ 9 „מן העולם החדש” — פרק רביעי'},'smetana-vltava':{en:'The Moldau (Vltava)',he:'המולדבה (ולטאבה)'},'tchaikovsky-sugar':{en:'The Nutcracker — Dance of the Sugar Plum Fairy',he:'מפצח האגוזים — ריקוד פיית שזיף הסוכר'},'mozart-turkish':{en:'Rondo Alla Turca',he:'רונדו אלה טורקה'},'bach-toccata':{en:'Toccata and Fugue in D minor',he:'טוקטה ופוגה ברה מינור'},'mendelssohn-wedding':{en:'Wedding March',he:'מארש החתונה'},'chopin-waltz69':{en:'Waltz in B minor, Op. 69 No. 2',he:'ואלס בסי מינור, אופ׳ 69 מס׳ 2'},'chopin-nocturne9':{en:'Nocturne in B-flat minor, Op. 9 No. 1',he:'נוקטורן בסי־במול מינור, אופ׳ 9 מס׳ 1'},brahms3:{en:'Symphony No. 3',he:'סימפוניה מס׳ 3'},'borodin-steppes':{en:'In the Steppes of Central Asia',he:'בערבות מרכז אסיה'},'chopin-nocturne48':{en:'Nocturne in C minor, Op. 48 No. 1',he:'נוקטורן בדו מינור, אופ׳ 48 מס׳ 1'}
};
let gameLang=localStorage.getItem('musicGameLang')||'ru';
function gt(key){return (GAME_I18N[gameLang]&&GAME_I18N[gameLang][key])||GAME_I18N.ru[key]||key}
function composerLabel(name){return gameLang==='ru'?name:(COMPOSER_I18N[name]?.[gameLang]||name)}
function workLabel(work){return gameLang==='ru'?work.work:(WORK_I18N[work.id]?.[gameLang]||work.work)}
function applyGameLanguage(){
 document.documentElement.lang=gameLang;document.documentElement.dir=gameLang==='he'?'rtl':'ltr';
 document.querySelectorAll('[data-i18n]').forEach(el=>{const v=gt(el.dataset.i18n);if(v!=null)el.textContent=v});
 document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('on',b.dataset.lang===gameLang));
 if(typeof quizLevel!=='undefined'&&document.getElementById('quizLevelDescription'))$('quizLevelDescription').textContent=gt('levels')[quizLevel];
 if(typeof currentWork!=='undefined'&&currentWork&&document.getElementById('composerAnswers')&&!$('composerAnswers').classList.contains('hidden')) naturalNewQuiz();
}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{gameLang=b.dataset.lang;localStorage.setItem('musicGameLang',gameLang);applyGameLanguage()});

// Localized pitch answers and result messages.
document.querySelectorAll('[data-pitch]').forEach(b=>b.onclick=()=>{if(pitchLocked)return;pitchLocked=true;const guess=b.dataset.pitch,correct=guess===pitchAnswer;b.classList.add(correct?'correct':'wrong');document.querySelector(`[data-pitch="${pitchAnswer}"]`).classList.add('correct');if(correct){pitchScore++;$('pitchScore').textContent=pitchScore;$('pitchFeedback').textContent=gt('correct')}else{$('pitchFeedback').textContent=`${gt('correctAnswer')}: ${gt(pitchAnswer)}.`}$('nextPitch').classList.remove('hidden')});
$('nextPitch').onclick=()=>{pitchRound++;if(pitchRound>10){const msg=pitchScore>=9?gt('pitchGreat'):pitchScore>=7?gt('pitchGood'):gt('pitchRetry');$('pitchFinish').innerHTML=`${gt('done')} <strong>${pitchScore}/10</strong><span class="muted">${msg}</span>`;$('pitchFinish').classList.remove('hidden');$('playPitch').classList.add('hidden');document.querySelector('.answers.three').classList.add('hidden');$('nextPitch').classList.add('hidden');return}newPitch()};

// Localized portrait cards and quiz feedback while keeping canonical composer names internally.
composerButton=function(name){const b=document.createElement('button');b.className='composer-card';b.dataset.composer=name;const img=document.createElement('img');img.src=composerPortraits[name]||'';img.alt=composerLabel(name);img.loading='lazy';img.decoding='async';img.onerror=()=>{img.classList.add('portrait-fallback');img.removeAttribute('src')};const label=document.createElement('span');label.textContent=composerLabel(name);b.append(img,label);b.onclick=()=>answerComposer(b,name);return b};
answerComposer=function(btn,name){if(quizLocked)return;stopNatural();quizLocked=true;const ok=name===currentWork.composer;[...$('composerAnswers').children].forEach(b=>{if(b.dataset.composer===currentWork.composer)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');else{quizScore++;$('quizScore').textContent=quizScore}$('quizFeedback').textContent=(ok?gt('correct')+' ':'')+`${composerLabel(currentWork.composer)} — «${workLabel(currentWork)}».`;$('nextQuiz').classList.remove('hidden')};
$('nextQuiz').onclick=()=>{quizRound++;if(quizRound>10){const msg=quizScore>=9?gt('quizGreat'):quizScore>=7?gt('quizGood'):gt('quizRetry');$('quizFinish').innerHTML=`${gt('done')} <strong>${quizScore}/10</strong><span class="muted">${msg}</span>`;$('quizFinish').classList.remove('hidden');$('playQuiz').classList.add('hidden');$('composerAnswers').classList.add('hidden');$('nextQuiz').classList.add('hidden');return}naturalNewQuiz()};

applyGameLanguage();