const $=id=>document.getElementById(id);
function hz(m){return 440*Math.pow(2,(m-69)/12)}
const gamePlayer=new Audio();gamePlayer.preload='auto';gamePlayer.playsInline=true;let currentAudioUrl=null;
function writeText(view,offset,text){for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i))}
function makeWav(notes,beat=.38,wave='sine'){const sampleRate=44100,noteDur=beat*.82,totalDur=Math.max(.2,notes.length*beat+.08),samples=Math.ceil(totalDur*sampleRate),buffer=new ArrayBuffer(44+samples*2),view=new DataView(buffer);writeText(view,0,'RIFF');view.setUint32(4,36+samples*2,true);writeText(view,8,'WAVE');writeText(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);writeText(view,36,'data');view.setUint32(40,samples*2,true);const attack=.018,release=.06,level=.78;for(let i=0;i<samples;i++){const t=i/sampleRate,idx=Math.floor(t/beat);let sample=0;if(idx<notes.length){const local=t-idx*beat;if(local<noteDur){const f=hz(notes[idx]),env=Math.min(1,local/attack,Math.max(0,(noteDur-local)/release)),phase=2*Math.PI*f*local;let raw=Math.sin(phase);if(wave==='triangle')raw=2/Math.PI*Math.asin(Math.sin(phase));sample=raw*env*level}}view.setInt16(44+i*2,Math.max(-1,Math.min(1,sample))*32767,true)}return new Blob([buffer],{type:'audio/wav'})}
async function playSeq(notes,beat=.38,type='triangle'){try{gamePlayer.pause();gamePlayer.currentTime=0;if(currentAudioUrl)URL.revokeObjectURL(currentAudioUrl);currentAudioUrl=URL.createObjectURL(makeWav(notes,beat,type));gamePlayer.src=currentAudioUrl;gamePlayer.volume=1;await gamePlayer.play();return new Promise(resolve=>{gamePlayer.onended=()=>resolve()})}catch(e){console.error(e);alert('Не удалось включить звук. Проверь громкость телефона и убедись, что звук для Safari не выключен.')}}
const chooser=$('chooser'),pitchGame=$('pitchGame'),quizGame=$('quizGame');function openGame(name){chooser.classList.add('hidden');pitchGame.classList.toggle('hidden',name!=='pitch');quizGame.classList.toggle('hidden',name!=='quiz');window.scrollTo({top:0,behavior:'smooth'});name==='pitch'?resetPitch():resetQuiz()}document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openGame(b.dataset.open));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{pitchGame.classList.add('hidden');quizGame.classList.add('hidden');chooser.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})});
let pitchLevel=1,pitchRound=1,pitchScore=0,pitchAnswer='',pitchNotes=[],pitchLocked=false;const pitchAnswersBox=document.querySelector('.answers.three');
const levelTwoPatterns={upup:{ys:[72,45,18]},downdown:{ys:[18,45,72]},sameup:{ys:[55,55,20]},upsame:{ys:[72,28,28]},samedown:{ys:[28,28,72]},downsame:{ys:[18,62,62]},updown:{ys:[68,20,68]},downup:{ys:[20,68,20]},same:{ys:[45,45,45]}};
function pitchWord(key){if(typeof gt==='function')return gt(key);return key==='up'?'Вверх':key==='down'?'Вниз':'На месте'}
function contourSvg(ys){const[a,b,c]=ys;return `<svg viewBox="0 0 120 90" aria-hidden="true"><line x1="20" y1="${a}" x2="60" y2="${b}"/><line x1="60" y1="${b}" x2="100" y2="${c}"/><circle cx="20" cy="${a}" r="9"/><circle cx="60" cy="${b}" r="9"/><circle cx="100" cy="${c}" r="9"/></svg>`}
function handlePitchGuess(btn,guess){if(pitchLocked)return;pitchLocked=true;const correct=guess===pitchAnswer;btn.classList.add(correct?'correct':'wrong');const right=pitchAnswersBox.querySelector(`[data-pitch-answer="${pitchAnswer}"]`)||pitchAnswersBox.querySelector(`[data-pitch="${pitchAnswer}"]`);if(right)right.classList.add('correct');if(correct){pitchScore++;$('pitchScore').textContent=pitchScore;$('pitchFeedback').textContent=typeof gt==='function'?gt('correct'):'Верно!'}else if(pitchLevel===2)$('pitchFeedback').textContent='Правильный рисунок показан зелёным.';else $('pitchFeedback').textContent=`Правильный ответ: ${pitchWord(pitchAnswer)}.`;$('nextPitch').classList.remove('hidden');if(typeof showGameReward==='function')showGameReward(correct)}
function renderPitchAnswers(){pitchAnswersBox.replaceChildren();pitchAnswersBox.className=pitchLevel===2?'answers pitch-patterns':'answers three';if(pitchLevel===2){Object.entries(levelTwoPatterns).forEach(([key,p])=>{const b=document.createElement('button');b.className='pitch-pattern';b.dataset.pitchAnswer=key;b.innerHTML=contourSvg(p.ys);b.setAttribute('aria-label',key);b.onclick=()=>handlePitchGuess(b,key);pitchAnswersBox.append(b)});return}const defs=[['up','↑'],['same','='],['down','↓']];defs.forEach(([key,symbol])=>{const b=document.createElement('button');b.dataset.pitch=key;b.dataset.pitchAnswer=key;const span=document.createElement('span');span.textContent=pitchWord(key);b.append(document.createTextNode(symbol),span);b.onclick=()=>handlePitchGuess(b,key);pitchAnswersBox.append(b)})}
document.querySelectorAll('.level[data-level]').forEach(b=>b.onclick=()=>{pitchLevel=+b.dataset.level;document.querySelectorAll('.level[data-level]').forEach(x=>x.classList.toggle('on',x===b));resetPitch()});
const rand=(a,b)=>a+Math.floor(Math.random()*(b-a+1));const step=()=>rand(2,7);
function makeLevelTwoNotes(key,start){const a=step(),b=step();switch(key){case'upup':return[start,start+a,start+a+b];case'downdown':return[start,start-a,start-a-b];case'sameup':return[start,start,start+a];case'upsame':return[start,start+a,start+a];case'samedown':return[start,start,start-a];case'downsame':return[start,start-a,start-a];case'updown':return[start,start+a,start+a-b];case'downup':return[start,start-a,start-a+b];default:return[start,start,start]}}
function newPitch(){pitchLocked=false;$('pitchFeedback').textContent='';$('nextPitch').classList.add('hidden');renderPitchAnswers();let start=rand(52,68);if(pitchLevel===1){const choices=['up','down','same'];pitchAnswer=choices[rand(0,2)];if(pitchAnswer==='same')pitchNotes=[start,start];else{const dir=pitchAnswer==='up'?1:-1;pitchNotes=[start,start+dir*rand(2,9)]}}else if(pitchLevel===2){const keys=Object.keys(levelTwoPatterns);pitchAnswer=keys[rand(0,keys.length-1)];pitchNotes=makeLevelTwoNotes(pitchAnswer,start);while(Math.min(...pitchNotes)<48||Math.max(...pitchNotes)>76){start=rand(54,66);pitchNotes=makeLevelTwoNotes(pitchAnswer,start)}}else{const choices=['up','down','same'];pitchAnswer=choices[rand(0,2)];const count=4;if(pitchAnswer==='same')pitchNotes=Array(count).fill(start);else{const dir=pitchAnswer==='up'?1:-1;pitchNotes=[start];for(let i=1;i<count;i++){start+=dir*rand(1,5);pitchNotes.push(start)}}}$('pitchRound').textContent=`${pitchRound}/10`}
function resetPitch(){pitchRound=1;pitchScore=0;$('pitchScore').textContent='0';$('pitchFinish').classList.add('hidden');$('playPitch').classList.remove('hidden');pitchAnswersBox.classList.remove('hidden');newPitch()}$('playPitch').onclick=async()=>{await playSeq(pitchNotes,.42,'sine')};$('nextPitch').onclick=()=>{pitchRound++;if(pitchRound>10){$('pitchFinish').innerHTML=`Готово! <strong>${pitchScore}/10</strong>`;$('pitchFinish').classList.remove('hidden');$('playPitch').classList.add('hidden');pitchAnswersBox.classList.add('hidden');$('nextPitch').classList.add('hidden');return}newPitch()};
const works=[{composer:'Людвиг ван Бетховен',work:'Симфония №5',notes:[67,67,67,63,65,65,65,62]}];const composers=[...new Set(works.map(x=>x.composer))];let quizRound=1,quizScore=0,currentWork=null,quizLocked=false;function pickAnswers(correct){const others=composers.filter(x=>x!==correct).sort(()=>Math.random()-.5).slice(0,3);return[...others,correct].sort(()=>Math.random()-.5)}function newQuiz(){}function resetQuiz(){if(typeof naturalNewQuiz==='function')naturalNewQuiz()}function answerComposer(){}