from pathlib import Path
p=Path('app.html')
s=p.read_text(encoding='utf-8')
if 'softPulseAudioCtx' in s: raise SystemExit(0)
old='''   <div id="${prefix}videoPanel" class="mode-panel hidden">\n     <p class="small">Можно просто двигаться. Не обязательно танцевать «красиво».</p>\n     <div class="video-wrap hidden" id="${prefix}CameraWrap"><video id="${prefix}Camera" autoplay muted playsinline></video></div>'''
new='''   <div id="${prefix}videoPanel" class="mode-panel hidden">\n     <p class="small">Можно просто двигаться. Не обязательно танцевать «красиво».</p>\n     <div class="small" style="margin-top:10px">Мягкий пульс с тихой квинтой</div>\n     <div class="chips" id="${prefix}PulseDurations"><button type="button" class="chip" data-pulse-minutes="2">2 мин</button><button type="button" class="chip selected" data-pulse-minutes="3">3 мин</button><button type="button" class="chip" data-pulse-minutes="4">4 мин</button><button type="button" class="chip" data-pulse-minutes="5">5 мин</button></div>\n     <button type="button" class="btn secondary" id="${prefix}PulseBtn">◉ Включить мягкий пульс</button>\n     <div id="${prefix}PulseStatus" class="small">Основной тон 250–300 Гц · квинта звучит тише</div>\n     <div class="video-wrap hidden" id="${prefix}CameraWrap"><video id="${prefix}Camera" autoplay muted playsinline></video></div>'''
assert old in s
s=s.replace(old,new,1)
oldbind=" $(prefix+'VoiceBtn').onclick=()=>recordStateVoice(prefix);\n $(prefix+'CameraBtn').onclick=()=>openCamera(prefix);"
newbind=" $(prefix+'VoiceBtn').onclick=()=>recordStateVoice(prefix);\n $(prefix+'PulseBtn').onclick=()=>toggleSoftPulse(prefix);\n document.querySelectorAll(`#${prefix}PulseDurations [data-pulse-minutes]`).forEach(b=>b.onclick=()=>{document.querySelectorAll(`#${prefix}PulseDurations [data-pulse-minutes]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');stateStore[prefix].pulseMinutes=Number(b.dataset.pulseMinutes)});stateStore[prefix].pulseMinutes=3;\n $(prefix+'CameraBtn').onclick=()=>openCamera(prefix);"
assert oldbind in s
s=s.replace(oldbind,newbind,1)
anchor='function bestVideoMime(){'
code=r'''let softPulseAudioCtx=null;const softPulseNodes={};
function stopSoftPulse(prefix,finished=false){const n=softPulseNodes[prefix];if(!n)return;clearTimeout(n.stopTimer);const now=n.ctx.currentTime;try{n.master.gain.cancelScheduledValues(now);n.master.gain.setValueAtTime(Math.max(.0001,n.master.gain.value),now);n.master.gain.exponentialRampToValueAtTime(.0001,now+2.5)}catch(e){}setTimeout(()=>{try{n.root.stop();n.fifth.stop();n.pulseLfo.stop();n.pitchLfo.stop()}catch(e){}},2700);delete softPulseNodes[prefix];const btn=$(prefix+'PulseBtn'),status=$(prefix+'PulseStatus');if(btn)btn.textContent='◉ Включить мягкий пульс';if(status)setText(status,finished?'Пульс мягко завершился.':'Основной тон 250–300 Гц · квинта звучит тише')}
async function toggleSoftPulse(prefix){if(softPulseNodes[prefix]){stopSoftPulse(prefix);return}try{Object.keys(softPulseNodes).forEach(k=>stopSoftPulse(k));if(!softPulseAudioCtx)softPulseAudioCtx=new (window.AudioContext||window.webkitAudioContext)();const ctx=softPulseAudioCtx;if(ctx.state==='suspended')await ctx.resume();const root=ctx.createOscillator(),fifth=ctx.createOscillator(),rootGain=ctx.createGain(),fifthGain=ctx.createGain(),master=ctx.createGain(),pulseLfo=ctx.createOscillator(),pulseDepth=ctx.createGain(),pitchLfo=ctx.createOscillator(),pitchDepth=ctx.createGain(),fifthPitch=ctx.createGain();root.type=fifth.type='sine';root.frequency.value=275;fifth.frequency.value=412.5;rootGain.gain.value=.78;fifthGain.gain.value=.22;pulseLfo.type='sine';pulseLfo.frequency.value=.68;pulseDepth.gain.value=.075;pitchLfo.type='sine';pitchLfo.frequency.value=.055;pitchDepth.gain.value=25;fifthPitch.gain.value=1.5;pitchLfo.connect(pitchDepth);pitchDepth.connect(root.frequency);pitchDepth.connect(fifthPitch);fifthPitch.connect(fifth.frequency);pulseLfo.connect(pulseDepth);pulseDepth.connect(master.gain);root.connect(rootGain);fifth.connect(fifthGain);rootGain.connect(master);fifthGain.connect(master);master.connect(ctx.destination);const now=ctx.currentTime;master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.24,now+2.2);root.start();fifth.start();pulseLfo.start();pitchLfo.start();const minutes=stateStore[prefix].pulseMinutes||3;const stopTimer=setTimeout(()=>stopSoftPulse(prefix,true),minutes*60000);softPulseNodes[prefix]={ctx,root,fifth,master,pulseLfo,pitchLfo,stopTimer};$(prefix+'PulseBtn').textContent='■ Остановить пульс';setText($(prefix+'PulseStatus'),`Звучит ${minutes} мин · 250–300 Гц + тихая квинта`)}catch(e){setText($(prefix+'PulseStatus'),'Не удалось включить звук: '+e.message)}}

'''
assert anchor in s
s=s.replace(anchor,code+anchor,1)
p.write_text(s,encoding='utf-8')
